[package]
name = "rax25"
version = "0.2.5"
edition = "2024"
license = "MIT"
authors = ["Thomas Habets <thomas@habets.se>"]
repository = "https://github.com/ThomasHabets/rax25"
description = "AX.25 connected mode implementation"
keywords = ["radio"]
# Last bumped because `std::time::Duration::from_mins`.
rust-version = "1.91"

[dependencies]
anyhow = "1.0.86"
bus = "2.4.1"
log = "0.4.22"
regex = "1.10.6"
serialport = { version = "4.5.0", optional = true }
tokio-serial = {version="5.4.4", optional = true }
#serialport = { path="../../src/serialport-rs"}
tokio = { version = "1.40.0", features = ["full"], optional=true }
clap = { version = "4.5.16", features = ["derive"] }

[features]
default = ["serial"]
async = ["dep:tokio", "dep:tokio-serial"]
serial = ["dep:serialport"]

[dev-dependencies]
stderrlog = "0.6.0"
ctrlc = "3.4.5"
agw = "0.6.0"
rand = "0.10.1"

[profile.release]
overflow-checks = true

[[example]]
name = "async_client"
required-features = ["async"]

[[example]]
name = "async_server"
required-features = ["async"]

[[example]]
name = "server"
required-features = ["serial"]

[[example]]
name = "client"
required-features = ["serial"]

[[example]]
name = "agw"
required-features = ["async"]

[[test]]
name = "async_tcp_examples"
required-features = ["async"]
