name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: apt install deps
      run:  sudo apt-get install -y libudev-dev tshark
    - name: rustup install nightly
      run:  rustup install nightly
    - name: Rustup install nightly clippy
      run:  rustup component add --toolchain nightly clippy
    - name: Cargo install deps
      run:  cargo install tickbox cargo-deny
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run:  CLEANUP=true tickbox --dir tickbox/pre-commit --disable-tui
